[Settings]
#ID = ""

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  # This is the directory to change to before starting a build.
#  base    = ""
#  publish = "dist/"
  # This will be your default build command
#  command = "echo 'default context'"
  # This is where we will look for your lambda functions
#  functions = "project/functions/"


# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/SPA/*"
  to = "/_spa.html"
  status = 200

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"


